### ISSUE TITLE
Only Works In Live Preview

### ISSUE THREAD

**Issue by Jnolcox** [clairefro/obsidian-plugin-etymology-lookup#1]
I am not sure if this is the intended function or if its required as I didn't see it in the documentation; button, hotkey, right-click and command palette all only work if in LE mode.

**Comment by clairefro** [comment]
Thanks for raising this! Confirmed this is a bug and will address

**Comment by clairefro** [comment]
Fixed in version `1.0.3`  ([commit](https://github.com/clairefro/obsidian-plugin-etymology-lookup/commit/247141e02d944ba6aedbffaed1a1a78d13aa8ffb))
